name:                haskbucks
version:             0.1.0.0
github:              "githubuser/haskbucks"
license:             Proprietary
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskbucks#readme>

when:
- condition: os(darwin)
  else:
    ghc-options:
    - -Werror
  then:
    ghc-options:
    - -Werror
    - -optP-Wno-nonportable-include-path
    # The above option works around https://github.com/haskell/cabal/issues/4739

dependencies:
- base >= 4.7 && < 5
- mtl
- stm
- containers
- async
- bytestring
- unix
- resource-pool
- postgresql-simple
- aeson
- hashable
- streaming
- resourcet
- file-embed

library:
  source-dirs: src

executables:
  haskbucks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskbucks

tests:
  haskbucks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskbucks
    - hspec
    - hspec-discover
